### ISSUE TITLE
Rate Limit reached every time I open the extension

### ISSUE THREAD

**Issue by guid-ooo** [mceck/clickup-kanbans-vscode#1]
<img width="344" alt="image" src="https://github.com/mceck/clickup-kanbans-vscode/assets/113428227/7f2f60e2-a061-469a-97f4-4318b64cb660">

Could this be due to the amount of lists in my workspace being too high?

**Comment by mceck** [comment]
yes it could be, to display the lists select i did a lot of recursive calls to build the full tree.
The result of that calls is cached for a while than, but if guess it crashed before.
I can try to make the lists fetch lazy to reduce the number of clickup api calls

Thank you for the feedback
